set(INCLUDE__STM32CUBEL4_EXTENSION TRUE)
set(PROJECT_UBINOS_LIBRARIES ${PROJECT_UBINOS_LIBRARIES} STM32CubeL4_extension)

set_cache_default(STM32CUBEL4__DTTY_STM32_UART_ENABLE FALSE BOOL "")

set_cache_default(STM32CUBEL4__DTTY_STM32_USBD_ENABLE FALSE BOOL "")

