////////


#cmakedefine01 INCLUDE__STM32CUBEL4_EXTENSION

#if (INCLUDE__STM32CUBEL4_EXTENSION == 1)

#cmakedefine01 STM32CUBEL4__DTTY_STM32_UART_ENABLE

#cmakedefine01 STM32CUBEL4__DTTY_STM32_USBD_ENABLE

#endif /* (INCLUDE__STM32CUBEL4_EXTENSION == 1) */

